### ISSUE TITLE
how do i run it? bcoz its in a sln file and cs file idk how to run help me out on my discord : ZODIAC#6894

### ISSUE THREAD

**Issue by ZODIAC0103** [nirajxhrestha/AIO-Checker#1]
how do i run it? bcoz its in a sln file and cs file idk how to run help me out on my discord : ZODIAC#6894

**Comment by nirajxhrestha** [comment]
you'll need to install visual studio 2019 and build the exe inorder to run it

**Comment by ZODIAC0103** [comment]
> you'll need to install visual studio 2019 and build the exe inorder to run it

can u reply me on discord how to do it from where i can download?

**Comment by nirajxhrestha** [comment]
sure dm me on MrWolf#1798
